# Generated by Django 5.1.7 on 2025-04-09 23:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12, verbose_name='Nome')),
                ('phone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Digite um número de telefone válido.', regex='^\\d{10,11}$')])),
                ('presenca', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Welcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
