# Generated by Django 5.1.7 on 2025-04-09 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_guests_welcome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guests',
            name='presenca',
        ),
    ]
