# Generated by Django 5.1.7 on 2025-04-10 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_guests_presenca'),
    ]

    operations = [
        migrations.AddField(
            model_name='guests',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='childs', to='main.guests'),
        ),
    ]
