# Generated by Django 5.1.7 on 2025-04-25 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_guests_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Confirmations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
